pointcloud_to_laserscan:
  ros__parameters:
    use_sim_time: false 
    target_frame: baal/base
    transform_tolerance: 0.1
    min_height: 0.3
    max_height: 0.9
    angle_min: -3.14159
    angle_max: 3.14159
    angle_increment: 0.0087
    range_min: 0.2
    range_max: 30.0
    queue_size: 10
    scan_time: 0.1
    use_inf: true
    inf_epsilon: 1.0
    output_qos: reliable
