# convert depth cloud, height is y axis downward,  but because realsense camera is upside down, so the y in optical frame become aligned with z in base_link
# height 0.2 hit the right level for bag 28
# height 0.0 hit the floor level for bag 28
# height -0.10 to 0.0 hit many the floor level and also still the obstacle for bag 28
#
# if not upside down, so min_height -0.2 is actually 0.2 meter above depth cam level, max_height 0 is camera level
pointcloud_to_laser_scan2:
  ros__parameters:
    use_sim_time: true
    input_topic: /camera/camera/depth/color/points
    output_topic: /scan2
    target_frame: camera_rgb_frame 
    transform_tolerance: 0.1
    min_height: -0.10
    max_height: 0.0 
    angle_min: -3.14159
    angle_max: 3.14159
    angle_increment: 0.0047
    range_min: 1.0
    range_max: 4.0
    queue_size: 10
    scan_time: 0.1
    use_inf: true
    inf_epsilon: 1.0
    output_qos: reliable
