sabertooth_2x32_serial:
  ros__parameters:
    port: /dev/ttyUSB0
    baudrate: 9600
    address: 128
    protocol: packet
    serial_timeout_sec: 0.1
    command_timeout_sec: 0.5
    max_linear_x: 1.0
    max_angular_z: 1.0
    motor_1_reversed: false
    motor_2_reversed: true
    deadband: 0.02
    publish_zero_on_timeout: true
